---
title: "Data Science Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    # vertical_layout: fill
---

```{r setup, include=FALSE}
library(dplyr)
library(flexdashboard)
library(igraph)
library(readxl)
library(sf)
# library(sfnetworks)
library(tidygraph)
library(tidyverse)
library(tmap)
library(geosphere)

tmap_mode("view")
```

Trains in London
=====================================
```{r, include=FALSE}
Stations = st_read("data/tfl_stations_new.json") %>%
  rename("Number of Lines" = "Number.of.Lines", "Station ID" = "Station.ID", "Line(s)" = "Lines")
Lines = st_read("data/tfl_lines_new.json")
Zones = st_read("data/tfl_zones.json")

colors = c(
  "#B26300", # Bakerloo
  "#DC241F", # Central
  "#FFD329", # Circle
  "#9364CC", # Crossrail
  "#e1eb5b", # Crossrail 2
  "#007D32", # District
  "#00AFAD", # DLR
  "#E0A9BE", # Hammersmith & City
  "#A1A5A7", # Jubliee
  "#9B0058", # Metropolitan
  "#000000", # Northern
  "#EF7B10", # Overground
  "#0019A8", # Piccadilly
  "#0098D8", # Victoria
  "#93CEBA" # Waterloo & City
)
```

### Tube System Map including Overground, DLR and Crossrail

```{r}
tm_shape(Zones)+
  tm_polygons(col="name", alpha=.2, legend.show=FALSE)+
  tm_shape(Lines) +
  tm_lines(col="Line", scale=3, palette = colors) +
  tm_shape(Stations) +
  tm_dots() 
```

Train Network Analysis
===============

### Total number of Tube stations including DLR

```{r}
#number <- nrow(nodes)
#valueBox(number, icon = "fa-subway")
```

Underpasses
================

```{r, include=FALSE}
# Import London map of boroughs
boroughs <- st_read("data/gis/London_Borough_Excluding_MHW.shp")
boroughs <- select(boroughs, NAME, GSS_CODE, HECTARES, NONLD_AREA, geometry)

height_restrictions <- read_excel("data/london_height-restrictions.xlsx")
# Extract simplified underpass data before conversion
underpasses_road_number <- select(height_restrictions, `Road number`)
# Extract categories from text and convert to double:
height_restrictions <- mutate(height_restrictions, `height_temp` = str_replace_all(`Height restriction (m)`, c("Between " = "", "Up to 3.0" = "0")))
height_restrictions <- mutate(height_restrictions, height = as.double(str_sub(`height_temp`, 1, 3)))
height_restrictions <- st_as_sf(height_restrictions, coords = c("Lng", "Lat"), crs = 4326) 

# Read data from OSM CSV export
osm_underpasses <- read.csv2("data/london_underpasses.csv", encoding = "UTF-8", sep = "\t", na.strings = c(""))
# data without a maximum clearance is not useful and mostly due to complex geometries
osm_underpasses <- filter(osm_underpasses, !is.na(maxheight))
osm_underpasses <- st_as_sf(osm_underpasses, coords = c("X.lon", "X.lat"), crs = 4236)
osm_underpasses <- st_transform(osm_underpasses, crs = 3875)

# Convert text strings to numbers
# Extension: convert imperial measurements to metres
osm_underpasses <- mutate(osm_underpasses, height = as.numeric(maxheight))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Underpasses based on National Statistics and Ordnance Survey

```{r}
tm_shape(boroughs) + tm_polygons() + tm_shape(height_restrictions) + tm_dots(col = "height")
```

> Contains National Statistics data © Crown copyright and database right [2015]
> Contains Ordnance Survey data © Crown copyright and database right [2015]

### Underpasses by borough (OS)

```{r}
ggplot(height_restrictions, mapping=aes(x = `Borough`, fill=factor(height))) + geom_bar() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0.0, vjust = 0.2)) +
  scale_y_continuous("Number of underpasses") +
  guides(fill = guide_legend(title = "minimum\nclearance"))
# X axis text orientation: https://ggplot2-book.org/polishing.html#theme-axis
```

Column {data-width=350}
-----------------------------------------------------------------------

### Underpasses based on OpenStreetMap

```{r}
tm_shape(boroughs) + tm_polygons() + tm_shape(osm_underpasses) + tm_dots(col = "height")
```

> © [OpenStreetMap](https://osm.org/copyright) contributors

### Underpasses by road number (OS)

```{r}
# Data queried via https://overpass-api.de/query_form.html
# [out:csv("name","highway","maxheight",::lat,::lon)]
# [timeout:180]
# ;
# (
#   way
#     ["maxheight"]
#     ["highway"]
#     (area:3600175342);
# );
# out center;
# >;
# out;
underpasses_road_number <- filter(underpasses_road_number, !is.na(`Road number`))
underpasses_road_number <- group_by(underpasses_road_number, `Road number`)
underpasses_road_number <- summarise(underpasses_road_number, number = n())
underpasses_road_number <- arrange(underpasses_road_number, desc(number))
knitr::kable(underpasses_road_number)
```

Accidents
==========
```{r, include = FALSE}
accidents <- read.csv2("data/london_2019-road-accidents.csv", encoding = "UTF-8", sep = ",")
```

Data source <https://roads.data.tfl.gov.uk/AccidentStats/Dev/2019-gla-data-extract-vehicle.csv>

Column {data-width=350}
-------------------------------------------------------------------------------------------

### Accidents per borough
```{r}
boroughaccidents <- group_by(accidents, Borough)
boroughaccidents <- summarise(boroughaccidents, number = n())
boroughaccidents <- mutate(boroughaccidents, Borough = str_replace(Borough, "-UPON-THAMES", " UPON THAMES"))
boroughaccidents <- mutate(boroughaccidents, Borough = str_replace(Borough, " & ", " AND "))
boroughaccidents <- rename(boroughaccidents, BName = Borough)
ba_spatial <- left_join(mutate(boroughs, BName = str_to_upper(NAME)), boroughaccidents)
ba_spatial <- select(ba_spatial, NAME, GSS_CODE, HECTARES, NONLD_AREA, number, geometry)
ba_spatial <- rename(ba_spatial, Accidents = number)

# Coloring doc: https://geocompr.github.io/post/2019/tmap-color-scales/#pretty
tm_shape(ba_spatial) + tm_polygons(col = "Accidents") + tm_legend(legend.outside = TRUE)
```

### Percentage of female drivers in accidents
```{r, size=200}
driver_sex <- group_by(accidents, Driver.Sex)
driver_sex <- summarise(driver_sex, n = n())
female_drivers <- filter(driver_sex, Driver.Sex == "2 FEMALE")[2]
male_drivers <- filter(driver_sex, Driver.Sex == "1 MALE")[2]
unidentified_drivers <- filter(driver_sex, Driver.Sex == "3 NOT TRACED")[2]
valueBox(round(female_drivers / (female_drivers + male_drivers + unidentified_drivers) * 100, digits = 0), icon = "fa-female")
```

### Median driver age
```{r}
driver_age <- summarise(filter(accidents, Driver.Age != 0), age = median(Driver.Age))
valueBox(driver_age)
```


Column {data-width=350}
-------------------------------------------------------------------------------------------

### Vehicle manoeuvres
```{r}
manoeuvres <- transmute(accidents, manoeuvre = str_sub(Vehicle.Manoeuvres, 4), skid = str_sub(Vehicle.Skidding, 3))
manoeuvres <- group_by(manoeuvres, manoeuvre, skid)
manoeuvres <- summarise(manoeuvres, number = n())
knitr::kable(manoeuvres)
```

Bus
=====================================