---
title: "TfL Bus Routes"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(httr)
library(jsonlite)
library(purrr)
library(readxl)
library(openxlsx)
library(sf)
library(sfnetworks)
library(tidygraph)
library(tmap)

data_day <- read.csv("data/all_bus_lines.csv") %>%
  mutate(switch = "day") %>%
  select(-X.1, -X)
data_night <- read.csv("data/all_bus_lines_night.csv") %>%
  mutate(switch = "night") %>%
  select(-X)

```
Bus Line App
===================================== 

COlumn {.sidebar} 
-----------------------------------------------------------------------

```{r}
data <- rbind(data_day, data_night)

choices <- as.character(data$lineId)

selectInput("lineId", 
          "Select Line: ", 
          unique(choices),
          selected = "1",
          multiple = FALSE)

```

Row 
-----------------------------------------------------------------------

### From

```{r}


renderValueBox({

  start_point <- data %>%
    filter(lineId == input$lineId) %>%
    select(name)

valueBox(start_point$name[1], 
          icon = "fa-arrow-circle-down")

})


```

### To


```{r}

renderValueBox({
  
  end_point <- data %>%
    filter(lineId == input$lineId)
    index <- end_point %>%
    nrow()
  
  valueBox(end_point$name[index], 
           icon = "fa-arrow-circle-up")
  
})

```

### Number of stops

```{r}


renderValueBox({
 
number_stops <- data %>%
  filter(lineId == input$lineId) %>%
  nrow()
  
valueBox(number_stops,
          icon = "fa-bus-alt")

    
})

```

### Distance

```{r}

renderValueBox({
 
distance <- data %>%
  filter(lineId == input$lineId) %>%
  filter(!is.na(Location_Easting)) %>%
  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700) %>%
  group_by(lineId) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") %>%
  st_length()

distance <- (distance/1000) %>%
  round(digits = 2)
  
valueBox(paste(distance, "km"),
          icon = "fa-road")
})

```

### Time

```{r}

renderValueBox({
 
data_dist <- data %>%
  filter(lineId == input$lineId) %>%
  filter(!is.na(Location_Easting))

distance <- data_dist %>%
  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700) %>%
  group_by(lineId) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") %>%
  st_length()

avg_speed <- (data_dist$Average_Speed[1] / 1.609)

time <- (((as.numeric(distance)/1000)*60)/(avg_speed)) %>%
  round(digits = 0)
  
valueBox(paste(time, "min"),
          icon = "fa-clock")
})


```

Column {data-width=650}
-----------------------------------------------------------------------

### Route

```{r}

# data <- st_as_sf(data, coords = c("Location_Easting", "Location_Northing"), crs = 27700)

bus_line <- reactive({
  data %>%
  filter(lineId == input$lineId) %>%
  filter(!is.na(Location_Easting)) %>%  
  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700)

 })

tmap_mode("view")

renderTmap({
  
net <- bus_line() %>%  
  group_by(lineId) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") %>%
  as_sfnetwork(directed = TRUE)  
  
# now lets add points
tm_shape(st_as_sf(net, "edges")) + tm_lines(id = c("Line" = "lineId"),
                                            scale = 2) +
  tm_shape(bus_line()) + tm_dots(col = "#dc241f",
                                 size = 0.04, 
                                 id = "name") + 
                                 #popup.vars = c("Line:" = "lineId"))
    tm_shape(st_as_sf(net, "nodes")) + tm_dots(col = "#0019a8", 
                                               size = 0.1,
                                               id = "name")
})

```

Day and Night Network Comparison
===================================== 

Column {data-width=650}
-----------------------------------------------------------------------

### The day network is clearly more dense

```{r}

net_day <- data_day %>%
  group_by(lineId) %>%
  filter(!is.na(Location_Easting)) %>%
  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") %>%
  mutate(length = as.numeric(st_length(geometry)))

tm_shape(net_day) + 
  tm_lines()

```

### Average length

```{r}


avg_length_day <- mean(net_day[["length"]]) / 1000
 

valueBox(paste(avg_length_day %>% round(2), "km"),
          icon = "fa-road")



```

Column {data-width=650}
-----------------------------------------------------------------------

### The night network's lines are longer on average

```{r}

net_night <- data_night %>%
  group_by(lineId) %>%
  filter(!is.na(Location_Easting)) %>%
  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") %>%
  mutate(length = as.numeric(st_length(geometry)))

tm_shape(net_night) + 
  tm_lines()


```

### Average length

```{r}


avg_length_night <- mean(net_night[["length"]]) / 1000
 

valueBox(paste(avg_length_night %>% round(2), "km"),
          icon = "fa-road")



```


Network Analysis - Nightbuses
===================================== 

Column {data-width=650}
-----------------------------------------------------------------------

### Betweenness centrality

```{r}

# simplified night bus network

bus_lines_mp <- read.csv("data/all_bus_lines_night.csv") %>%
  filter(!is.na(Location_Easting)) %>%
  group_by(parentId) %>%
  mutate(Location_Easting = mean(Location_Easting)) %>%
  mutate(Location_Northing = mean(Location_Northing))

# simplified bus stops
stop_mp <- bus_lines_mp %>%
  select(parentId, stationId, name, Location_Easting, Location_Northing) %>%
  unique()

# CREATE EDGE AND NODES FOR NETWORK DATA
# EVERY STATION FROM EVERY LINE GETS CONNECTED SEPERATELY

# first

#network_mp <- left_join(bus_lines_mp, stop_mp, by = "parentId") %>%
#  select(lineId, parentId, name.y, Location_Easting.y, Location_Northing.y) %>%
#  rename("Location_Easting" = Location_Easting.y, "Location_Northing" = Location_Northing.y, "name" = name.y) %>%
#  unique() %>%
#  ungroup() %>%
#  st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700) #%>%
#  group_by(lineId) %>%
#  summarise(do_union = FALSE) %>%
#  st_cast("LINESTRING")

nodes <- bus_lines_mp %>%
  select(X, lineId,parentId, Location_Easting, Location_Northing, name) %>%
  rename("nodeID" = X) %>%
  mutate(start = "start", end = "end") %>%
  gather(start_end, end, start:end) #%>%
  #st_as_sf(coords = c("Location_Easting", "Location_Northing"), crs = 27700)# %>%
  #arrange(lineId) 

nodes_start <- nodes %>%
  filter(start_end == "start") %>%
  group_by(lineId) %>% 
  mutate(Index_Group = row_number()) %>%
  filter(Index_Group != max(n())) %>%
  ungroup()

nodes_end <- nodes %>%
  filter(start_end == "end") %>%
  group_by(lineId) %>% 
  mutate(Index_Group = row_number()) %>%
  filter(Index_Group != 1) %>%
  ungroup() %>%
  mutate(nodeID = nodeID + 10000)  
    
edges <- cbind(D1 = nodes_start, D2 = nodes_end) %>%
  rename(c(D1.lineId, D1.Location_Easting, D1.Location_Northing, D2.Location_Easting, D2.Location_Northing),
         "lineId" = D1.lineId,
         "lat_start" = D1.Location_Easting, 
         "lon_start" = D1.Location_Northing, 
         "lat_end" = D2.Location_Easting, 
         "lon_end" = D2.Location_Northing) %>%
  select(lineId, D1.name, lat_start, lon_start, lat_end, lon_end) %>%
  unite(start_point, lat_start:lon_start, sep = "__") %>%
  unite(end_point, lat_end:lon_end, sep = "__") %>%
  mutate(Index = row_number()) %>% 
  gather(D1.name, point, start_point:end_point) %>%
  arrange(Index) %>%
  separate(point, c("lat", "lon"), sep = "__") %>%
  st_as_sf(coords = c("lat", "lon"), crs = 27700) %>%
  group_by(Index) %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING")
  
edges <- edges %>%
  mutate(edgeID = c(1:n()))

nodes <- edges %>%
  st_coordinates() %>%
  as_tibble() %>%
  rename(edgeID = L1) %>%
  group_by(edgeID) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  mutate(start_end = rep(c('start', 'end'), times = n()/2)) %>%
  mutate(xy = paste(.$X, .$Y)) %>% 
  mutate(nodeID = group_indices(., factor(xy, levels = unique(xy)))) %>%
  select(-xy)

source_nodes <- nodes %>%
  filter(start_end == "start") %>%
  pull(nodeID)

target_nodes <- nodes %>%
  filter(start_end == "end") %>%
  pull(nodeID)
  
edges = edges %>%
  mutate(from = source_nodes, to = target_nodes)

nodes <- nodes %>%
  distinct(nodeID, .keep_all = TRUE) %>%
  st_as_sf(coords = c('X', 'Y'), crs = 27700) %>%
  select(nodeID, geometry)
  #st_set_crs(st_crs(edges))

#network <- tbl_graph(nodes = nodes, edges = as_tibble(edges), directed = FALSE)

network <- sfnetwork(nodes, edges, directed = TRUE) %>%
  activate(edges) %>%
  mutate(length = st_length(geometry))
  
network <- network %>%  
  activate(nodes) %>%
  mutate(degree = centrality_degree()) %>%
  mutate(betweenness = centrality_betweenness(weights = as.numeric(length) + 0.0001)) %>%
  mutate(eigen = centrality_eigen()) %>%
  activate(edges) %>%
  mutate(betweenness = centrality_edge_betweenness(weights = as.numeric(length) + 0.0001))

tm_shape(network %>% activate(edges) %>% as_tibble() %>% st_as_sf()) + 
  tm_lines() + 
  tm_shape(network %>% activate(nodes) %>% as_tibble() %>% st_as_sf()) +
  tm_dots(col = "betweenness", size = "betweenness", palette = "cividis")


```


Column {data-width=650}
-----------------------------------------------------------------------

### Betweenness centrality

```{r}


tm_shape(network %>% activate(edges) %>% as_tibble() %>% st_as_sf()) + 
  tm_lines(col = "betweenness") + 
  tm_shape(network %>% activate(nodes) %>% as_tibble() %>% st_as_sf()) +
  tm_dots(col = "eigen", size = "degree", palette = "cividis")


```
